tempPos = read.csv("/home/morikie/Documents/Forschungspraktikum/C++/polar/scripts/resultUcontentPositive.csv", header=FALSE)
tempNeg = read.csv("/home/morikie/Documents/Forschungspraktikum/C++/polar/scripts/resultUcontentNegative.csv", header=FALSE)
tempFN = read.csv("/home/morikie/Documents/Forschungspraktikum/C++/polar/scripts/resultUcontentFN.csv", header=FALSE)
tempFP = read.csv("/home/morikie/Documents/Forschungspraktikum/C++/polar/scripts/resultUcontentFP.csv", header=FALSE)
tempTP = read.csv("/home/morikie/Documents/Forschungspraktikum/C++/polar/scripts/resultUcontentTP.csv", header=FALSE)
tempTN = read.csv("/home/morikie/Documents/Forschungspraktikum/C++/polar/scripts/resultUcontentTN.csv", header=FALSE)

xPos = seq(0, 491)
yPos = rep(0, 492)
xNeg = seq(0, 491)
yNeg = rep(0, 492)
xFN = seq(0, 491)
yFN = rep(0, 492)
xFP = seq(0, 491)
yFP = rep(0, 492)
xTP = seq(0, 491)
yTP = rep(0, 492)
xTN = seq(0, 491)
yTN = rep(0, 492)

for (i in 1:(length(yTP) - 1)) {
  yPos[i] = mean(tempPos[, i])
  yNeg[i] = mean(tempNeg[, i])
  yFN[i] = mean(tempFN[, i])
  yTP[i] = mean(tempTP[, i])
  yTN[i] = mean(tempTN[, i])
  yFP[i] = mean(tempFP[, i])
}

par(mfrow=c(3,2))
plot(xTP, yTP, main="FN data set", type="h", ylim=c(0,4))
axis(side=1, at=seq(200, 300, by=10))
plot(xTN, yTN, main="FP data set", type="h", ylim=c(0,4))
axis(side=1, at=seq(200, 300, by=10))
plot(xFN, yFN, main="FN data set", type="h", ylim=c(0,4))
axis(side=1, at=seq(200, 300, by=10))
plot(xFP, yFP, main="FP data set", type="h", ylim=c(0,4))
axis(side=1, at=seq(200, 300, by=10))
plot(xPos, yPos, main="Positive data set", type="h", ylim=c(0,4))
axis(side=1, at=seq(200, 300, by=10))
plot(xNeg, yNeg, main="Negative data set", type="h", ylim=c(0,4))
axis(side=1, at=seq(200, 300, by=10))
