tempPos = read.csv("/home/morikie/Documents/Forschungspraktikum/C++/polar/scripts/u-content/resultUcontentPositive.csv", header=FALSE)
tempNeg = read.csv("/home/morikie/Documents/Forschungspraktikum/C++/polar/scripts/u-content/resultUcontentNegative.csv", header=FALSE)
tempFN = read.csv("/home/morikie/Documents/Forschungspraktikum/C++/polar/scripts/u-content/resultUcontentFN.csv", header=FALSE)
tempFP = read.csv("/home/morikie/Documents/Forschungspraktikum/C++/polar/scripts/u-content/resultUcontentFP.csv", header=FALSE)
tempTP = read.csv("/home/morikie/Documents/Forschungspraktikum/C++/polar/scripts/u-content/resultUcontentTP.csv", header=FALSE)
tempTN = read.csv("/home/morikie/Documents/Forschungspraktikum/C++/polar/scripts/u-content/resultUcontentTN.csv", header=FALSE)

xPos = seq(0, 490)
yPos = rep(0, 491)
xNeg = seq(0, 490)
yNeg = rep(0, 491)
xFN = seq(0, 490)
yFN = rep(0, 491)
xFP = seq(0, 490)
yFP = rep(0, 491)
xTP = seq(0, 490)
yTP = rep(0, 491)
xTN = seq(0, 490)
yTN = rep(0, 491)

for (i in 1:(length(yTP) - 1)) {
  yPos[i] = mean(tempPos[, i])
  yNeg[i] = mean(tempNeg[, i])
  yFN[i] = mean(tempFN[, i])
  yTP[i] = mean(tempTP[, i])
  yTN[i] = mean(tempTN[, i])
  yFP[i] = mean(tempFP[, i])
}

par(mfrow=c(3,2), oma=c(0,0,4,0))
plot(xTP[200:400], yTP[200:400], main="TP data set", type="h", ylim=c(0,5))
axis(side=1, at=seq(200, 300, by=10))
plot(xTN[200:400], yTN[200:400], main="TN data set", type="h", ylim=c(0,5))
axis(side=1, at=seq(200, 300, by=10))
plot(xFN[200:400], yFN[200:400], main="FN data set", type="h", ylim=c(0,5))
axis(side=1, at=seq(200, 300, by=10))
plot(xFP[200:400], yFP[200:400], main="FP data set", type="h", ylim=c(0,5))
axis(side=1, at=seq(200, 300, by=10))
plot(xPos[200:400], yPos[200:400], main="Positive data set", type="h", ylim=c(0,5))
axis(side=1, at=seq(200, 300, by=10))
plot(xNeg[200:400], yNeg[200:400], main="Negative data set", type="h", ylim=c(0,5))
axis(side=1, at=seq(200, 300, by=10))
mtext("U content distribution", outer = TRUE, cex = 1.5)